// Generated by `pnpm --filter @outrn/api fixtures`. Do not edit by hand: change the scenario in
// packages/api/scripts/fixtures.ts and regenerate. Every response here came from the real API.
import type { ApiError, Area, AreasResponse, OpsRunDetail, OpsRunList, PlaceDetails, RecommendationRequest, RecommendationResponse } from "../index.js";
import fx_areas from "./areas.json" with { type: "json" };
import fx_recommendations_les_1 from "./recommendations/les-1.json" with { type: "json" };
import fx_recommendations_les_2 from "./recommendations/les-2.json" with { type: "json" };
import fx_recommendations_les_3 from "./recommendations/les-3.json" with { type: "json" };
import fx_recommendations_les_4 from "./recommendations/les-4.json" with { type: "json" };
import fx_recommendations_bronxville_1 from "./recommendations/bronxville-1.json" with { type: "json" };
import fx_recommendations_bronxville_2 from "./recommendations/bronxville-2.json" with { type: "json" };
import fx_recommendations_bronxville_3 from "./recommendations/bronxville-3.json" with { type: "json" };
import fx_recommendations_bronxville_4 from "./recommendations/bronxville-4.json" with { type: "json" };
import fx_recommendations_bars_1 from "./recommendations/bars-1.json" with { type: "json" };
import fx_recommendations_bars_2 from "./recommendations/bars-2.json" with { type: "json" };
import fx_recommendations_bars_3 from "./recommendations/bars-3.json" with { type: "json" };
import fx_recommendations_bars_4 from "./recommendations/bars-4.json" with { type: "json" };
import fx_recommendations_family_1 from "./recommendations/family-1.json" with { type: "json" };
import fx_recommendations_family_2 from "./recommendations/family-2.json" with { type: "json" };
import fx_recommendations_cuisine_1 from "./recommendations/cuisine-1.json" with { type: "json" };
import fx_recommendations_cuisine_2 from "./recommendations/cuisine-2.json" with { type: "json" };
import fx_recommendations_events_1 from "./recommendations/events-1.json" with { type: "json" };
import fx_recommendations_fewer_1 from "./recommendations/fewer-1.json" with { type: "json" };
import fx_recommendations_none_1 from "./recommendations/none-1.json" with { type: "json" };
import fx_recommendations_expired_1 from "./recommendations/expired-1.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000002 from "./places/00000000-0000-4000-8000-000000000002.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000003 from "./places/00000000-0000-4000-8000-000000000003.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000004 from "./places/00000000-0000-4000-8000-000000000004.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000005 from "./places/00000000-0000-4000-8000-000000000005.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000006 from "./places/00000000-0000-4000-8000-000000000006.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000007 from "./places/00000000-0000-4000-8000-000000000007.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000008 from "./places/00000000-0000-4000-8000-000000000008.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000009 from "./places/00000000-0000-4000-8000-000000000009.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000000a from "./places/00000000-0000-4000-8000-00000000000a.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000000b from "./places/00000000-0000-4000-8000-00000000000b.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000000c from "./places/00000000-0000-4000-8000-00000000000c.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000000d from "./places/00000000-0000-4000-8000-00000000000d.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000000f from "./places/00000000-0000-4000-8000-00000000000f.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000010 from "./places/00000000-0000-4000-8000-000000000010.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000011 from "./places/00000000-0000-4000-8000-000000000011.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000012 from "./places/00000000-0000-4000-8000-000000000012.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000013 from "./places/00000000-0000-4000-8000-000000000013.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000014 from "./places/00000000-0000-4000-8000-000000000014.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000015 from "./places/00000000-0000-4000-8000-000000000015.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000016 from "./places/00000000-0000-4000-8000-000000000016.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000017 from "./places/00000000-0000-4000-8000-000000000017.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000018 from "./places/00000000-0000-4000-8000-000000000018.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000019 from "./places/00000000-0000-4000-8000-000000000019.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000001a from "./places/00000000-0000-4000-8000-00000000001a.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000001c from "./places/00000000-0000-4000-8000-00000000001c.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000001d from "./places/00000000-0000-4000-8000-00000000001d.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000001e from "./places/00000000-0000-4000-8000-00000000001e.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000001f from "./places/00000000-0000-4000-8000-00000000001f.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000020 from "./places/00000000-0000-4000-8000-000000000020.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000021 from "./places/00000000-0000-4000-8000-000000000021.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000022 from "./places/00000000-0000-4000-8000-000000000022.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000023 from "./places/00000000-0000-4000-8000-000000000023.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000024 from "./places/00000000-0000-4000-8000-000000000024.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000026 from "./places/00000000-0000-4000-8000-000000000026.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000028 from "./places/00000000-0000-4000-8000-000000000028.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000029 from "./places/00000000-0000-4000-8000-000000000029.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000002a from "./places/00000000-0000-4000-8000-00000000002a.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000002b from "./places/00000000-0000-4000-8000-00000000002b.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000002e from "./places/00000000-0000-4000-8000-00000000002e.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_00000000002f from "./places/00000000-0000-4000-8000-00000000002f.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000031 from "./places/00000000-0000-4000-8000-000000000031.json" with { type: "json" };
import fx_places_00000000_0000_4000_8000_000000000032 from "./places/00000000-0000-4000-8000-000000000032.json" with { type: "json" };
import fx_ops_evaluate from "./ops/evaluate.json" with { type: "json" };
import fx_ops_runs from "./ops/runs.json" with { type: "json" };
import fx_errors_cursor_expired from "./errors/cursor-expired.json" with { type: "json" };
import fx_errors_validation from "./errors/validation.json" with { type: "json" };
import fx_errors_unknown_area from "./errors/unknown-area.json" with { type: "json" };
import fx_errors_cursor_invalid from "./errors/cursor-invalid.json" with { type: "json" };
import fx_errors_not_found from "./errors/not-found.json" with { type: "json" };
import fx_errors_unauthorized from "./errors/unauthorized.json" with { type: "json" };
import fx_errors_unavailable from "./errors/unavailable.json" with { type: "json" };

export interface Scenario {
  id: string;
  /** How the mock lists it in GET /v1/areas. Real areas keep their id; mock-only ones start with "mock-". */
  area: Area;
  title: string;
  description: string;
  /** The request that produced it (areaId rewritten to the scenario's). */
  request: RecommendationRequest;
  /** Page 1, 2, ... chained by nextCursor / prevCursor. Empty when the search itself fails. */
  pages: RecommendationResponse[];
  /** Name of the error fixture the search returns instead. */
  error?: string;
  /** Page 2 returns the "cursor-expired" error. */
  expiresAfterFirstPage?: boolean;
}

export interface ErrorFixture {
  status: number;
  body: ApiError;
}

export const areas = fx_areas as unknown as AreasResponse;

export const scenarios: Scenario[] = [
  { id: "les", area: {"id":"les","name":"Lower East Side (test point)","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Lower East Side, Saturday 6:30pm", description: "Walking, 3 hours free. Several pages: follow nextCursor.", request: {"areaId":"les","windowMinutes":180}, pages: [fx_recommendations_les_1, fx_recommendations_les_2, fx_recommendations_les_3, fx_recommendations_les_4] as unknown as RecommendationResponse[] },
  { id: "bronxville", area: {"id":"bronxville","name":"Bronxville (test point)","timezone":"America/New_York","defaultTravelMode":"drive","center":{"lat":40.941,"lon":-73.835}}, title: "Bronxville, Saturday 7:30pm", description: "Driving (the area default), 2 hours free; travel includes parking.", request: {"areaId":"bronxville","windowMinutes":120}, pages: [fx_recommendations_bronxville_1, fx_recommendations_bronxville_2, fx_recommendations_bronxville_3, fx_recommendations_bronxville_4] as unknown as RecommendationResponse[] },
  { id: "bars", area: {"id":"mock-bars","name":"Mock · bars, date night","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Bars on a date", description: "Narrowed to bars. One has hours confirmed by a call; another's place page shows a stale check and disagreeing sources.", request: {"areaId":"mock-bars","windowMinutes":180,"company":"date","categories":["bar"]}, pages: [fx_recommendations_bars_1, fx_recommendations_bars_2, fx_recommendations_bars_3, fx_recommendations_bars_4] as unknown as RecommendationResponse[] },
  { id: "family", area: {"id":"mock-family","name":"Mock · family, age limits","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Family, late, bars", description: "A family with no ages given: a bar that is usually 21+ is Check first with a required age caveat.", request: {"areaId":"mock-family","windowMinutes":120,"company":"family","categories":["bar"]}, pages: [fx_recommendations_family_1, fx_recommendations_family_2] as unknown as RecommendationResponse[] },
  { id: "cuisine", area: {"id":"mock-cuisine","name":"Mock · a cuisine","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Italian tonight", description: "Asking for a cuisine: only food places serving it, pizza included in Italian. Each card lists `cuisines` and its summary leads with one.", request: {"areaId":"mock-cuisine","windowMinutes":120,"cuisines":["italian"]}, pages: [fx_recommendations_cuisine_1, fx_recommendations_cuisine_2] as unknown as RecommendationResponse[] },
  { id: "events", area: {"id":"mock-events","name":"Mock · a scheduled event","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Theatre tonight", description: "A scheduled performance: kind \"event\" with start and end times.", request: {"areaId":"mock-events","windowMinutes":240,"categories":["theatre"]}, pages: [fx_recommendations_events_1] as unknown as RecommendationResponse[] },
  { id: "fewer", area: {"id":"mock-fewer","name":"Mock · fewer than three","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Free outdoors, 1 hour, 2:30am", description: "Fewer than three qualify: `insufficient` explains and offers relaxations. Never pad.", request: {"areaId":"mock-fewer","windowMinutes":60,"budget":{"kind":"free"},"categories":["park","viewpoint","waterfront"]}, pages: [fx_recommendations_fewer_1] as unknown as RecommendationResponse[] },
  { id: "none", area: {"id":"mock-none","name":"Mock · nothing fits","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Nothing fits", description: "Zero items, with relaxations.", request: {"areaId":"mock-none","windowMinutes":30,"budget":{"kind":"free"},"categories":["museum"]}, pages: [fx_recommendations_none_1] as unknown as RecommendationResponse[] },
  { id: "expired", area: {"id":"mock-expired","name":"Mock · expired pages","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Pages expired", description: "Page 1 is fine; asking for page 2 returns CURSOR_EXPIRED with `restart`.", request: {"areaId":"mock-expired","windowMinutes":120}, pages: [fx_recommendations_expired_1] as unknown as RecommendationResponse[], expiresAfterFirstPage: true },
  { id: "error", area: {"id":"mock-error","name":"Mock · service unavailable","timezone":"America/New_York","defaultTravelMode":"walk","center":{"lat":40.7185,"lon":-73.988}}, title: "Backend down", description: "The search fails with UNAVAILABLE (503, retryable).", request: {"areaId":"mock-error","windowMinutes":180}, pages: [] as unknown as RecommendationResponse[], error: "unavailable" },
];

/** GET /v1/places/:id for every place any scenario shows. */
export const places: Record<string, PlaceDetails> = {
  "00000000-0000-4000-8000-000000000002": fx_places_00000000_0000_4000_8000_000000000002 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000003": fx_places_00000000_0000_4000_8000_000000000003 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000004": fx_places_00000000_0000_4000_8000_000000000004 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000005": fx_places_00000000_0000_4000_8000_000000000005 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000006": fx_places_00000000_0000_4000_8000_000000000006 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000007": fx_places_00000000_0000_4000_8000_000000000007 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000008": fx_places_00000000_0000_4000_8000_000000000008 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000009": fx_places_00000000_0000_4000_8000_000000000009 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000000a": fx_places_00000000_0000_4000_8000_00000000000a as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000000b": fx_places_00000000_0000_4000_8000_00000000000b as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000000c": fx_places_00000000_0000_4000_8000_00000000000c as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000000d": fx_places_00000000_0000_4000_8000_00000000000d as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000000f": fx_places_00000000_0000_4000_8000_00000000000f as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000010": fx_places_00000000_0000_4000_8000_000000000010 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000011": fx_places_00000000_0000_4000_8000_000000000011 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000012": fx_places_00000000_0000_4000_8000_000000000012 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000013": fx_places_00000000_0000_4000_8000_000000000013 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000014": fx_places_00000000_0000_4000_8000_000000000014 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000015": fx_places_00000000_0000_4000_8000_000000000015 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000016": fx_places_00000000_0000_4000_8000_000000000016 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000017": fx_places_00000000_0000_4000_8000_000000000017 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000018": fx_places_00000000_0000_4000_8000_000000000018 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000019": fx_places_00000000_0000_4000_8000_000000000019 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000001a": fx_places_00000000_0000_4000_8000_00000000001a as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000001c": fx_places_00000000_0000_4000_8000_00000000001c as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000001d": fx_places_00000000_0000_4000_8000_00000000001d as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000001e": fx_places_00000000_0000_4000_8000_00000000001e as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000001f": fx_places_00000000_0000_4000_8000_00000000001f as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000020": fx_places_00000000_0000_4000_8000_000000000020 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000021": fx_places_00000000_0000_4000_8000_000000000021 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000022": fx_places_00000000_0000_4000_8000_000000000022 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000023": fx_places_00000000_0000_4000_8000_000000000023 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000024": fx_places_00000000_0000_4000_8000_000000000024 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000026": fx_places_00000000_0000_4000_8000_000000000026 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000028": fx_places_00000000_0000_4000_8000_000000000028 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000029": fx_places_00000000_0000_4000_8000_000000000029 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000002a": fx_places_00000000_0000_4000_8000_00000000002a as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000002b": fx_places_00000000_0000_4000_8000_00000000002b as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000002e": fx_places_00000000_0000_4000_8000_00000000002e as unknown as PlaceDetails,
  "00000000-0000-4000-8000-00000000002f": fx_places_00000000_0000_4000_8000_00000000002f as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000031": fx_places_00000000_0000_4000_8000_000000000031 as unknown as PlaceDetails,
  "00000000-0000-4000-8000-000000000032": fx_places_00000000_0000_4000_8000_000000000032 as unknown as PlaceDetails,
};

export const ops = { evaluate: fx_ops_evaluate as unknown as OpsRunDetail, runs: fx_ops_runs as unknown as OpsRunList };

export const errors: Record<string, ErrorFixture> = {
  "cursor-expired": fx_errors_cursor_expired as unknown as ErrorFixture,
  "validation": fx_errors_validation as unknown as ErrorFixture,
  "unknown-area": fx_errors_unknown_area as unknown as ErrorFixture,
  "cursor-invalid": fx_errors_cursor_invalid as unknown as ErrorFixture,
  "not-found": fx_errors_not_found as unknown as ErrorFixture,
  "unauthorized": fx_errors_unauthorized as unknown as ErrorFixture,
  "unavailable": fx_errors_unavailable as unknown as ErrorFixture,
};
