import { StyleSheet } from "react-native";
import { colors } from "./ui";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.paper },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    flexGrow: 1,
  },
  header: { paddingTop: 4, paddingBottom: 12 },
  demo: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.accent,
    paddingVertical: 4,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 48,
    marginBottom: 4,
  },
  title: {
    fontSize: 28,
    lineHeight: 32,
    letterSpacing: -1,
    fontWeight: "600",
    flex: 1,
  },
  actions: { flexDirection: "row", alignItems: "center" },
  action: {
    width: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  back: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 44,
    gap: 2,
    alignSelf: "flex-start",
  },
  tabs: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  tab: {
    minHeight: 44,
    justifyContent: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  selectedTab: { borderBottomColor: colors.ink },
  tabText: { fontSize: 14, lineHeight: 20, fontWeight: "500" },
  fits: {
    marginLeft: "auto",
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: colors.sage,
    borderRadius: 24,
  },
  fitsSelected: { backgroundColor: colors.ink },
  fitsText: { fontSize: 13, lineHeight: 19, fontWeight: "500" },
  search: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: colors.sage,
    paddingLeft: 12,
    marginBottom: 8,
    gap: 8,
  },
  input: {
    flex: 1,
    minWidth: 0,
    fontFamily: "DMSans",
    fontSize: 16,
    color: colors.ink,
    minHeight: 44,
  },
  nameInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    fontFamily: "DMSans",
    fontSize: 16,
    color: colors.ink,
    minHeight: 48,
  },
  columns: { gap: 13 },
  tile: { marginBottom: 23 },
  category: { fontSize: 12, lineHeight: 17, color: colors.muted, marginTop: 7 },
  placeName: {
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: -0.25,
    fontWeight: "600",
    marginVertical: 3,
  },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  status: { fontSize: 12, lineHeight: 17, color: colors.muted, marginTop: 4 },
  open: { color: colors.green },
  ready: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.green,
    marginTop: 4,
    fontWeight: "600",
  },
  age: { fontSize: 12, lineHeight: 18, color: colors.accent, marginTop: 4 },
  collectionCard: { marginBottom: 24 },
  covers: {
    flexDirection: "row",
    gap: 3,
  },
  emptyCover: {
    flex: 1,
    height: 165,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.sage,
  },
  collectionCaption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  collectionName: { flex: 1, fontSize: 17, lineHeight: 23, fontWeight: "600" },
  context: { fontSize: 12, lineHeight: 18, color: colors.muted, marginTop: 10 },
  credits: { fontSize: 11, lineHeight: 16, color: colors.muted, marginTop: 4 },
  notice: {
    backgroundColor: colors.warm,
    padding: 12,
    borderRadius: 12,
    marginTop: 12,
  },
  empty: { paddingVertical: 56, gap: 16, alignItems: "center" },
  emptyTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyCopy: { color: colors.muted, textAlign: "center", maxWidth: 290 },
  label: { fontWeight: "600" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  textAction: { minHeight: 44, justifyContent: "center" },
  link: {
    color: colors.green,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 48,
    gap: 16,
  },
  toast: {
    position: "absolute",
    bottom: 12,
    left: 16,
    right: 16,
    maxWidth: 560,
    alignSelf: "center",
    borderRadius: 14,
    backgroundColor: colors.ink,
    paddingLeft: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toastText: { color: colors.paper, fontSize: 13, lineHeight: 19 },
  undo: {
    minHeight: 44,
    minWidth: 44,
    justifyContent: "center",
    marginLeft: "auto",
  },
  dismiss: {
    minHeight: 44,
    width: 44,
    alignItems: "center",
    justifyContent: "center",
  },
});
